server:
  port: 8085

spring:
  dubbo:
    application:
      name: demo-provider
    base-package: com.cn  # dubbo服务发布者所在的包
    registry:
      address: 127.0.0.1                   # zookeeper注册中心的地址
      port: 2181                           # zookeeper注册中心的端口
    protocol:
      name: dubbo
      serialization: hessian2
    provider:
      retries: 0                           # 服务调用重试次数，服务发布者不给重试，让服务调用者自己重试

  redis:
      host: localhost
      password:
      port: 6379
      timeout: 5000
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1